apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: keycloak-hostname-patch.yaml
  - path: keycloak-tls-cert-patch.yaml
  - path: realm-import-job-patch.yaml
