# Certificate for Kiali's internal gRPC connection to Istiod.
# The kiali-server Helm chart mounts this as the "kiali-cert" volume from the
# secret named "istio.kiali-service-account". In Istio ≤1.7 this secret was
# auto-created by Citadel; newer Istio dropped that behaviour, so we create it
# explicitly via cert-manager.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kiali-service-account-cert
  namespace: istio-system
spec:
  secretName: istio.kiali-service-account
  issuerRef:
    name: eck-2026-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - kiali.istio-system.svc
    - kiali.istio-system.svc.cluster.local
  duration: 8760h    # 1 year
  renewBefore: 720h  # 30 days
